trigger:
  branches:
    include:
      - main

jobs:
- job: SignPDFJob
  displayName: 'Digitally Sign PDF'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
    displayName: 'Set up Python environment'

  - script: |
      python -m pip install --upgrade pip
      pip install PyPDF2 pikepdf
    displayName: 'Install Python dependencies'

  - script: |
      python sign_pdf.py
    displayName: 'Run PDF Signing Script'

  - task: PublishPipelineArtifact@1
    displayName: 'Upload Signed PDF'
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/signed_output.pdf'
      artifactName: 'signed_pdf'
      publishLocation: 'pipeline'
