trigger:
  branches:
    include:
      - main

jobs:
- job: SignPDFJob
  displayName: 'Digitally Sign PDF'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
    displayName: 'Set up Python environment'

  - task: Bash@3
    displayName: 'Install dependencies'
    inputs:
      targetType: 'inline'
      script: |
        sudo apt-get update
        sudo apt-get install -y qpdf openssl

  - task: Bash@3
    displayName: 'Run PDF Signing Script'
    inputs:
      targetType: 'inline'
      script: |
        chmod +x sign_pdf.sh
        ./sign_pdf.sh

  - script: ls -R $(System.DefaultWorkingDirectory)
    displayName: 'List Files for Debugging'

  - task: PublishPipelineArtifact@1
    displayName: 'Upload Signed PDF'
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/signed_output.pdf'
      artifactName: 'signed_pdf'
      publishLocation: 'pipeline'
