# azure-pipelines.yml
trigger:
  branches:
    include:
      - main  # or the branch you want to trigger on

jobs:
- job: SignPDFJob
  displayName: 'Digitally Sign PDF'
  pool:
    vmImage: 'ubuntu-latest'  # Use an Ubuntu VM image

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
    displayName: 'Set up Python environment'

  - task: Bash@3
    displayName: 'Install dependencies'
    inputs:
      targetType: 'inline'
      script: |
        sudo apt-get update
        sudo apt-get install -y qpdf openssl

  - task: Bash@3
    displayName: 'Run PDF Signing Script'
    inputs:
      targetType: 'inline'
      script: |
        chmod +x sign_pdf.sh
        ./sign_pdf.sh

  - task: PublishPipelineArtifact@1
    displayName: 'Upload Signed PDF'
    inputs:
      targetPath: 'signed_output.pdf'  # Adjust if your output file has a different name
      artifactName: 'signed_pdf'
      publishLocation: 'pipeline'
